from cagojeiger/cuda:10.1-base 
MAINTAINER cagojeiger@naver.com

RUN apt-get update -y
RUN git clone https://github.com/kangheeyong/STUDY-machine-learning.git /home/STUDY-machine-learning
RUN pip3 install tensorflow-gpu

